title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://msina.me

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

aux_links:
  "Just the Docs on GitHub":
    - "//github.com/just-the-docs/just-the-docs"
